// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTnPERbSYYa99oJLUyVSagyVT8r6jqK54',
    appId: '1:389562969162:android:3db37f4370156370354ab3',
    messagingSenderId: '389562969162',
    projectId: 'coffee-shop-9d510',
    databaseURL: 'https://coffee-shop-9d510-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-9d510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9GAliXv5cU1QEuFG5psoPaU_KZuOS4w',
    appId: '1:389562969162:ios:aaad5a9b49b90db0354ab3',
    messagingSenderId: '389562969162',
    projectId: 'coffee-shop-9d510',
    databaseURL: 'https://coffee-shop-9d510-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-9d510.firebasestorage.app',
    iosClientId: '389562969162-60nkt3il14bcj2jj1uis63sr9ln60va0.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9GAliXv5cU1QEuFG5psoPaU_KZuOS4w',
    appId: '1:389562969162:ios:aaad5a9b49b90db0354ab3',
    messagingSenderId: '389562969162',
    projectId: 'coffee-shop-9d510',
    databaseURL: 'https://coffee-shop-9d510-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-9d510.firebasestorage.app',
    iosClientId: '389562969162-60nkt3il14bcj2jj1uis63sr9ln60va0.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4YTdloK0C5rLfWnAWIeSngLdjk5jyZo',
    appId: '1:389562969162:web:b4b20a65b64847ea354ab3',
    messagingSenderId: '389562969162',
    projectId: 'coffee-shop-9d510',
    authDomain: 'coffee-shop-9d510.firebaseapp.com',
    databaseURL: 'https://coffee-shop-9d510-default-rtdb.firebaseio.com',
    storageBucket: 'coffee-shop-9d510.firebasestorage.app',
    measurementId: 'G-MF59430583',
  );
}
